name: 'Docker Image Transfer'
description: 'Pulls a Docker image from a registry and pushes it to another.'

inputs:
  source:
    description: 'Source Docker image repository (e.g., docker.io/user/source-repo:tag)'
    required: true
  destination:
    description: 'Destination Docker image repository (e.g., docker.io/user/source-repo:tag)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SOURCE: ${{ inputs.source }}
    DESTINATION: ${{ inputs.destination }}
