name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: Test Action
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Transfer Docker Image
        uses: ./
        with:
          source: docker.io/hello-world:latest
          destination: localhost:5001/hello-world:latest

      - name: Clear images
        run: |
          docker image rm docker.io/hello-world:latest
          docker image rm localhost:5001/hello-world:latest

      - name: Check Docker Image
        run: |
          docker pull localhost:5001/hello-world:latest
          docker run localhost:5001/hello-world:latest
