name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: Test Action
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Transfer Docker Image
        uses: ./
        with:
          source-repo: docker.io/hello-world:latest
          destination-repo: hello-world:latest
          destination-registry: localhost:5001
